/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Entidades.Medico;
import Entidades.TextPrompt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mco_a
 */
public class EditarMedico extends javax.swing.JFrame {

    private ListaMedicos padre;
    private int medicoSelecIndex;
    private boolean isCreando;
    
    String [] especialidad = new String [23];
    /**
     * Creates new form EditarMedico
     */
    public EditarMedico() {
        initComponents();
    }
    
    public EditarMedico(ListaMedicos padre) {
        initComponents();
        this.padre = padre;
        isCreando = true;
        especialidad[0] = "Medicina Familiar";
        especialidad[1]="Medicina Interna";
        especialidad[2]="Endocrinología";
        especialidad[3]="Pediatría";
        especialidad[4]="Gineco-osbtetricia";
        especialidad[5]="Cirugía";
        especialidad[6]="Psiquiatría";
        especialidad[7]="Cardiología";
        especialidad[8]="Dermatología";
        especialidad[9]="Gastroenterología";
        especialidad[10]="Infectología";
        especialidad[11]="Nefrología";
        especialidad[12]="Oftalmología";
        especialidad[13]="Otorrinolaringología";
        especialidad[14]="Neumología";
        especialidad[15]="Neurología";
        especialidad[16]="Radiología";
        especialidad[17]="Anestesiología";
        especialidad[18]="Oncología";
        especialidad[19]="Patología";
        especialidad[20]="Urología";
        especialidad[21]="Medicina física y rehabilitación";
        especialidad[22]="Medicina Intensiva";
        
        cbEspecialidad.setModel(new DefaultComboBoxModel<>(especialidad));
        
        TextPrompt txtPrompt = new TextPrompt("Nombre", txtNombre);
        TextPrompt txtPrompt1 = new TextPrompt("CMP", txtCMP);
    }
    
    public EditarMedico(ListaMedicos padre, Medico medico, int medicoSelecIndex) {
        initComponents();
        this.padre = padre;
        this.medicoSelecIndex = medicoSelecIndex;
         isCreando = false;
         
         txtNombre.setText(
                medico.getNombre());
        
         txtCMP.setText(
                medico.getNombre());
         
         //cbSexo.setText(paciente.getSexo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCMP = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina Familiar", "Medicina Interna", "Endocrinología", "Pediatría", "Gineco-osbtetricia", "Cirugía", "Psiquiatría", "Cardiología", "Dermatología", "Gastroenterología", "Infectología", "Nefrología", "Oftalmología", "Otorrinolaringología", "Neumología", "Neurología", "Radiología", "Anestesiología", "Oncología", "Patología", "Urología", "Medicina física y rehabilitación", "Medicina Intensiva" }));
        cbEspecialidad.setBorder(null);
        jPanel1.add(cbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 290, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/TextField1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtCMP.setBackground(new java.awt.Color(255, 255, 255));
        txtCMP.setBorder(null);
        jPanel1.add(txtCMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 20));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Btn-Verde1.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Btn-Rojo1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/TextField1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/TextField1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, -1, -1));

        jLabel2.setText("Médico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/EditarPaciente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String nombre = txtNombre.getText();
        String CMP = txtCMP.getText();
        
        
        if (nombre.isEmpty() || CMP.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Completa todo los campos");
            return; // No continuamos si los campos están vacíos
        }
        
        Medico medico = getMedicoDesdePantalla();
        if(isCreando){
            this.padre.agregarMedico(medico);
        }else{
            this.padre.editarMedico(medico, 
                    this. medicoSelecIndex);
        }
        Cerrar();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private Medico getMedicoDesdePantalla() throws NumberFormatException {
        
        String nombre = txtNombre.getText();
        String CMP = txtCMP.getText();
        String especialidad = this.cbEspecialidad.getSelectedItem().toString();
        //int index = this.cbSexo.getSelectedIndex();
        //String sexo = this.sexos[index];
        
        Medico medico =
                new Medico(nombre, CMP, especialidad);
        return medico;
    }                             
    
    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Cerrar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseExited

    private void Cerrar(){
       this.padre.setVisible(true);
       this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCMP;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
