/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Entidades.Medico;
import Entidades.Paciente;
import Entidades.TextPrompt;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mco_a
 */
public class ListaPacientes extends javax.swing.JFrame {

    private NuevaCita hijo;
    private EditarPaciente padre;
    
    private List<Paciente> pacientes 
            = new ArrayList<>();
    
    private DefaultListModel listaPacientes 
            = new DefaultListModel();
    /**
     * Creates new form ListaPacientes
     */
    public ListaPacientes() {
        initComponents();
    }
    
    public ListaPacientes(EditarPaciente padre) {
        initComponents();
        this.padre = padre;
    }
    public ListaPacientes(NuevaCita hijo){
        initComponents();
        this.hijo = hijo;
        TextPrompt txtPrompt = new TextPrompt("Buscar", txtBusqueda);
            lstPacientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Detectar doble clic
                    int selectedIndex = lstPacientes.getSelectedIndex();
                    if (selectedIndex >= 0) {
                        Paciente pacienteSeleccionado = pacientes.get(selectedIndex);
                        hijo.txtPaciente.setText(pacienteSeleccionado.toString());
                        hijo.setVisible(true); // Mostrar la ventana NuevaCita
                        dispose(); // Cerrar la ventana actual (ListaMedicos)
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPacientes = new javax.swing.JList<>();
        btnCrearPaciente = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setBorder(null);
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jScrollPane1.setBorder(null);

        lstPacientes.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstPacientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, -1));

        btnCrearPaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Btn-Verde1.png"))); // NOI18N
        btnCrearPaciente.setText("Crear Paciente");
        btnCrearPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearPacienteMouseExited(evt);
            }
        });
        jPanel1.add(btnCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Btn-Rojo1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/JList1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Btn-Azul1.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/TextField1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("Lista de Pacientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ListarPacientes.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 478, 349));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        txtBusqueda.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            // No realiza búsqueda automática aquí
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
            // Cuando se borra el texto, se restaura la lista completa
                if (txtBusqueda.getText().trim().isEmpty()) {
                    lstPacientes.setModel(listaPacientes);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            // No realiza búsqueda automática aquí
            }
        });
        
        // Obtiene el texto de búsqueda en minúsculas
        String textoBusqueda = txtBusqueda.getText().trim().toLowerCase();

        if (textoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, ingresa un término de búsqueda "
                            + "antes de hacer clic en Buscar.", 
                    "Campo de búsqueda vacío", 
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            // Crea un modelo para los resultados
            DefaultListModel resultadosModel = new DefaultListModel(); 

            for (Paciente paciente : pacientes) {
                // Obtiene el codigo y nombre del estudiante en minúsculas
                String dniPaciente = 
                        paciente.getDni().toLowerCase(); 
                
                String nombrePaciente =
                        paciente.getNombre().toLowerCase();
            
                // Agrega los cursos al modelo de resultados
                if (nombrePaciente.contains(textoBusqueda) || 
                        dniPaciente.contains(textoBusqueda))
                {
                    resultadosModel.addElement(
                            paciente.getTexto()); 
                }
            }
        
            if (resultadosModel.isEmpty()) {
                // Muestra un mensaje si no se encontraron resultados
                JOptionPane.showMessageDialog(this, 
                        "No se encontraron resultados"
                                + " para la búsqueda.",
                        "Sin resultados", 
                        JOptionPane.INFORMATION_MESSAGE
                );
            
                // Restablece el modelo original
                lstPacientes.setModel(listaPacientes);
            } else {
                // Configura el modelo de resultados
                lstPacientes.setModel(resultadosModel);
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnCrearPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPacienteMouseClicked
        EditarPaciente pantalla = new EditarPaciente(this);
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearPacienteMouseClicked

    public void agregarPaciente(Paciente paciente){
        
        pacientes.add(paciente);
        actualizarLista();
    }
    
    public void editarPaciente(Paciente paciente, int index){
        
        Paciente pacienteAnterior = pacientes.get(index);
        
        pacienteAnterior.setNombre(
                paciente.getNombre());
 
        actualizarLista();
    }
    
    public void actualizarLista(){
        listaPacientes.removeAllElements();
        for(Paciente paciente: this.pacientes){
            listaPacientes.addElement(
                    paciente.getTexto());
        }
        lstPacientes.setModel(listaPacientes);
    }
    
    private void btnCrearPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPacienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPacienteMouseEntered

    private void btnCrearPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPacienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPacienteMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
       
        this.dispose();
        this.hijo.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrearPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPacientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
